name: dart_di
description: A dependency containerization package for Dart language
version: 0.0.2
repository: https://github.com/kardenvan7/dart_di

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
